# Generated by Django 5.2.8 on 2026-01-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_adminuser_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
