# Generated by Django 5.2.8 on 2026-01-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
